"""This program converts the txt index generated by index.sh to a json index
txt index contains pairs of lines with the name of a ./data/pgXX.txt file and the title of
the world facts book of the cia in the ./data/pgXX.txt file
"""
from Utils import list_of_lines
from Utils import write_json

source = './results/txt_index.txt'
target = './results/json_index.txt'

lines = [line for line in list_of_lines(source)]

index = dict()
k = 0
while k < len(lines):
    index[lines[k]] = lines[k+1]
    k += 2

write_json(target, index)